### ISSUE TITLE
MFSDA fails with one covariate

### ISSUE THREAD

**Issue by vicory** [DCBIA-OrthoLab/MFSDA_Python#3]
Current code makes assumption that the covariates read from the file has 2d shape (i.e. rows and columns) while the numpy reader will collapse the second dimension if there is only 1 column.

**Comment by jcfr** [comment]
Closing. This has been fixed in https://github.com/DCBIA-OrthoLab/MFSDA_Python/commit/ac7471da3227266d5989d308cdf72e8fa8a16fcd (ENH: Support running with one covariate )

@vicory  Please, re-open if this was closed by mistake
