### ISSUE TITLE
Code can fail for singular matrices

### ISSUE THREAD

**Issue by vicory** [DCBIA-OrthoLab/MFSDA_Python#4]
I've occasionally run into the code failing when trying to invert a singular matrix. Code could check for this error and use a pseudo-inverse instead.

**Comment by jcfr** [comment]
Closing. This was fixed in https://github.com/DCBIA-OrthoLab/MFSDA_Python/commit/a813c2ce8d2a86a8ac855ba5794babda6c528944 (BUG: Fix crash with singular matrix )

@vicory  Please re-open if this was closed by mistake
